version: '3'

services:
  frontend:
    container_name: frontend
    build: './frontend'
    ports:
      - "3000:3000"
    networks:
      - mynet
    

  quiz:
    container_name: quiz
    build: './quiz'
    ports:
      - "3001:3001"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
    ipam:
      driver: default
    
