apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz
spec:
  selector:
    matchLabels:
      app: quiz
  template:
    metadata:
      labels:
        app: quiz
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: gcr.io/${PROJECT_ID}/quiz
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: quiz
spec:
  type: ClusterIP
  selector:
    app: quiz
  ports:
  - name: grpc
    port: 3001
    targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - name: server
          image: gcr.io/${PROJECT_ID}/frontend
          ports:
          - containerPort: 3000
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 3000

          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/"
              port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
---